server:
  port: 8080

upstreams:
  - name: api_server_1
    url: http://localhost:3001
    weight: 2
  
  - name: api_server_2
    url: http://localhost:3002
    weight: 1
  
  - name: web_server
    url: http://localhost:4000
    weight: 1

routes:
  - name: api_route
    match:
      path: /api/*
    upstreams:
      - api_server_1
      - api_server_2
  
  - name: admin_route
    match:
      host: admin.example.com
    upstream: api_server_1
  
  - name: web_route
    match:
      host: "*.example.com"
    upstream: web_server
  
  - name: default_route
    match:
      path: /*
    upstreams:
      - api_server_1
      - api_server_2
      - web_server